run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
  modules-download-mode: readonly
  go: "1.21"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/your-username/redis-wrapper
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  revive:
    min-confidence: 0
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "disableStutteringCheck"
  staticcheck:
    go: "1.19"
    checks: ["all"]
  stylecheck:
    go: "1.19"
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  unparam:
    check-exported: false
  unused:
    go: "1.19"

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - depguard
    - exhaustivestruct
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goheader
    - gomnd
    - gomoddirectives
    - gomodguard
    - gosec
    - lll
    - maintidx
    - nakedret
    - nestif
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - promlinter
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - gosec
        - unparam
    - path: cmd/
      linters:
        - gocritic
        - gosec
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - gocritic
      text: "string `.*` has \\d+ occurrences, make it a constant"
    - linters:
        - stylecheck
      text: "ST1003:"
    - linters:
        - revive
      text: "exported: exported method .*\\..* should have comment or be unexported"
  exclude-use-default: false
  exclude:
    # Exclude some gosec messages
    - "G404: Use of weak random number generator"
    - "G601: Implicit memory aliasing in for loop"
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false